apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::473571294504:role/eksctl-eks-pj-cluster-ServiceRole-qYi2mP6BBLSJ
        cloudwatch.amazonaws.com/log-group: /aws/eks/eks-pj/cluster/logs
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 473571294504.dkr.ecr.us-east-1.amazonaws.com/coworking:0.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_HOST
          value: postgresql-service
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: admin
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: postgres
      restartPolicy: Always
